// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRh7bDAnxBUPJBWdUt671eQ9O5gnNvbw',
    appId: '1:494288787271:web:e577728eff0764f517de62',
    messagingSenderId: '494288787271',
    projectId: 'diet-quest-app',
    authDomain: 'diet-quest-app.firebaseapp.com',
    storageBucket: 'diet-quest-app.firebasestorage.app',
    measurementId: 'G-SZN129JJ1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZs-pU15Undcc0YfW5OE4MnGPOf5pwb0Q',
    appId: '1:494288787271:android:0065669c09dcd12517de62',
    messagingSenderId: '494288787271',
    projectId: 'diet-quest-app',
    storageBucket: 'diet-quest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwOohp3Y1ZVvOGAuLavkNed7653mwCco',
    appId: '1:494288787271:ios:1fbc23972182a7b117de62',
    messagingSenderId: '494288787271',
    projectId: 'diet-quest-app',
    storageBucket: 'diet-quest-app.firebasestorage.app',
    iosBundleId: 'com.example.dietQuestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwOohp3Y1ZVvOGAuLavkNed7653mwCco',
    appId: '1:494288787271:ios:1fbc23972182a7b117de62',
    messagingSenderId: '494288787271',
    projectId: 'diet-quest-app',
    storageBucket: 'diet-quest-app.firebasestorage.app',
    iosBundleId: 'com.example.dietQuestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeRh7bDAnxBUPJBWdUt671eQ9O5gnNvbw',
    appId: '1:494288787271:web:da4c5c64a346877d17de62',
    messagingSenderId: '494288787271',
    projectId: 'diet-quest-app',
    authDomain: 'diet-quest-app.firebaseapp.com',
    storageBucket: 'diet-quest-app.firebasestorage.app',
    measurementId: 'G-CKR4Q5VE77',
  );
}
